### ISSUE TITLE
Concussion Creeper Teleporting Player to Void

### ISSUE THREAD

**Issue by AmmolS** [SleepyTrousers/EnderZoo#92] opened 2015-05-21 04:06 UTC
Concussion Creepers can teleport players that are underground into the void. This can be a problem as players will have no way of retrieving their lost items or finding their grave. This was tested in the Overworld.

Tested with: 
Ender Zoo - 1.0.11.28
Forge - 10.13.3.1408

**Comment by theriftwalker** [comment] 2015-05-25 03:51
Happened to myself while flying (Magic Crops Armor).

Ender Zoo V 1.0.11.28
Forge - 10.13.3.1408

Can provide full modlist (Or look up Cybermancy Pack on Curse) on request.
![image](https://cloud.githubusercontent.com/assets/9586220/7791529/058f06f4-025f-11e5-841e-1484932a19e6.png)

**Comment by TheGreen** [comment] 2015-05-30 08:20
Happened to my brother as well, luckily he had a jetpack so he could fly until i had ported him out ^^

**Comment by mrhappypenguin** [comment] 2015-06-07 04:18
I can confirm this as well. I just had this happen on the Infinity Pack from FTB. It teleported me about 200M below bedrock.

EnderZoo v1.0.11.28

**Comment by Cooolaid** [comment] 2015-06-07 10:49
I can confirm this.  - I lost EXTREMELY expensive items twice.
Can someone pls tell me how to completely disable this damn creeper.?
Or I will have no choice but to completely uninstall this mod permanently.
I am a bit upset right now.

**Comment by Unrepentant-Atheist** [comment] 2015-06-07 11:19
Yea, can confirm. Happend to me once, lost shitton of expensive items, but c'est la vie. Moving on.

**Comment by BurgundyBadger** [comment] 2015-06-22 13:58
This is happening to players on my server.
I'm going to just change the teleport range to 0 for temp fix.
Ender Zoo - 1.0.11.28

**Comment by cocopuffs99** [comment] 2015-07-01 19:41
This is happening to players on my server as well

**Comment by Hund** [comment] 2015-07-02 10:25
If you loose your stuff and you have Openblocks a admin can restore the items via the command "/op_inventory restore".

**Comment by p455w0rd** [comment] 2015-08-31 16:11
So I noticed in changelog for 1.0.13.30 in the changelog it says "- #92 Concussion Creeper Teleporting to Void" - doesnt say whether the actual fix is included. So I come here and the issue is still open. Has this been fixed in the latest releases?

**Comment by CrazyPants** [comment] 2015-08-31 17:18
It has. I just forgot to close the issue.

**Closed** 2016-01-11 15:29 UTC
Labels: bug, Code Complete
