### ISSUE TITLE
Concussion Creeper explosion near bedrock is bad!

### ISSUE THREAD

**Issue by firebrim** [SleepyTrousers/EnderZoo#122] opened 2016-01-31 21:23 UTC
Please make sure  the Concussion Creepers can't teleport the player below bedrock level.

**Comment by b0bst3r** [comment] 2016-01-31 22:00
What version of Ender Zoo is this?

**Comment by HenryLoenwind** [comment] 2016-01-31 22:11
a very outdated one, I'd guess. That bug was fixed ages ago. Jul 20, 2015 to be exact.

**Comment by b0bst3r** [comment] 2016-01-31 22:23
Yeah that's the reason I asked, I thought it was fixed in 1974 :D

**Comment by firebrim** [comment] 2016-01-31 22:34
Im using EnderZoo-1.8.9-1.1.2

**Comment by HenryLoenwind** [comment] 2016-02-01 10:49
so it seems to be a regression.

CrazyPants?

**Closed** 2016-03-22 07:35 UTC
Labels: bug
